#we use java
language: java

#we add the java development kit (jdk)
jdk:
  - openjdk8
services:
  - docker
before_install:
  - mvn clean
  - echo "$DOCKER_PASSWORD" | docker login  -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:8-jdk-alpine
script:
  - mvn deploy


