sudo: required

#we use java
language: java

#we add the java development kit (jdk)
jdk:
  - openjdk8

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}
    - IMAGE_NAME=anastayaa/spring-boot-travisci

script:
  - ./mvnw clean install -B
before_install:
  - docker pull $IMAGE_NAME
  - docker run --rm -d --name web-app -p 8080:8080 $DOCKER_USERNAME/$IMAGE_NAME
after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - docker build -t $IMAGE_NAME:$COMMIT .
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME
